<h1>넘파이(Numpy)</h1>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [6]:
a = np.array([1,2,3,4,5])
print(type(a))
a

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [5]:
b = np.array([[10,20,30], [60,70,80]])
b

array([[10, 20, 30],
       [60, 70, 80]])

In [7]:
print(b.ndim)
print(b.shape)

2
(2, 3)


In [8]:
print(a.ndim)
print(a.shape)

1
(5,)


In [11]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
a = np.full((2,2),7)
print(a)

[[7 7]
 [7 7]]


In [15]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
a = np.random.random((2,2))
print(a)

[[0.96991214 0.91854667]
 [0.54633971 0.27037048]]


<h2>arange()</h2>

In [26]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]
<class 'numpy.ndarray'>


<h2>reshape()</h2>

In [23]:
a = np.array(np.arange(30)).reshape((5,6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
<class 'numpy.ndarray'>


<h2>Numpy 슬라이싱</h2>

In [27]:
a = np.array([[1,2,3],[4,5,6]])

In [32]:
b=a[0:2,0:2]
print(b)

[[1 2]
 [4 5]]


In [29]:
b=a[0,:] # 첫번째 행 출력
print(b)

[1 2 3]


In [31]:
b=a[:,1] # 두번째 열 출력
print(b)

[2 5]


<h2>Numpy 정수 인덱싱</h2>

In [33]:
a = np.array([[1,2],[4,5],[7,8]])
b = a[[2,1],[1,0]] # a[[row2,row1],[col1,col0]]을 의미
print(b) # [row2col1(8) row1col0(4)] 출력

[8 4]


<h2>Numpy 연산</h2>

In [34]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [35]:
b = x + y
#b = np.add(x, y)와 동일함
print(b)

[5 7 9]


In [38]:
b = x - y
#b = np.subtract(x, y)와 동일함
print(b)

[-3 -3 -3]


In [39]:
b = b * x
#b = np.muliply(b, x)와 동일함
print(b)

[-3 -6 -9]


In [40]:
b = b / x
#b = np.add(b, x)와 동일함
print(b)

[-3. -3. -3.]


In [41]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.dot(a,b) #dot 연산 - 백터와 행렬의 곱 OR 행렬곱
print(c)

[[19 22]
 [43 50]]
